name: kuyfit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  shared_preferences_android: 2.1.4
  flutter_local_notifications: 16.0.0
  path_provider_android: 2.2.14
